### ISSUE TITLE
Randomly failing tests

### ISSUE THREAD

**Issue by Arthasasyan** [axibase/atsd-api-test#553]
Some of the current tests are failing randomly. Because of that build is sometimes broken and fixed after restart. I suggest leaving links to these tests here to fix them afterwards.

**Comment by Arthasasyan** [comment]
https://github.com/axibase/atsd-api-test/blob/189e11108b54a7c20b843e2938bf030d64adc0a2/src/test/java/com/axibase/tsd/api/method/series/SeriesQueryTransformationWithDifferentForecastTest.java#L130

Could not borrow object from pool:
```java
Run 17: SeriesQueryTransformationWithDifferentForecastTest.testGoodResponse:130->SeriesMethod.querySeriesAsList:192->SeriesMethod.querySeries:55->SeriesMethod.querySeries:59->BaseMethod.executeApiRequest:133->BaseMethod.executeRequest:143 » NotChecked
```

**Comment by Arthasasyan** [comment]
https://github.com/axibase/atsd-api-test/blob/189e11108b54a7c20b843e2938bf030d64adc0a2/src/test/java/com/axibase/tsd/api/method/series/SeriesQueryTransformationsWithoutForecastPermutationsTest.java#L186

Original exception messages (I changed `NotCheckedException` thrown by `BaseMethod` to text of original exception for test):

```java
test(com.axibase.tsd.api.method.series.SeriesQueryTransformationsWithoutForecastPermutationsTest)  Time elapsed: 2.998 sec  <<< FAILURE!
com.axibase.tsd.api.util.NotCheckedException: Timeout waiting for idle object
        at com.axibase.tsd.api.method.series.SeriesQueryTransformationsWithoutForecastPermutationsTest.test(SeriesQueryTransformationsWithoutForecastPermutationsTest.java:186)

test(com.axibase.tsd.api.method.series.SeriesQueryTransformationsWithoutForecastPermutationsTest)  Time elapsed: 0.002 sec  <<< FAILURE!
com.axibase.tsd.api.util.NotCheckedException: Timeout waiting for idle object
        at com.axibase.tsd.api.method.series.SeriesQueryTransformationsWithoutForecastPermutationsTest.test(SeriesQueryTransformationsWithoutForecastPermutationsTest.java:186)
```

**Comment by Arthasasyan** [comment]
@raipc @unrealwork can incrementation of `DEFAULT_MAX_TOTAL` and `DEFAULT_MAX_IDLE` resolve the problem with these two cases?

**Comment by Arthasasyan** [comment]
```java
com.axibase.tsd.api.method.sql.clause.with.SqlWithTimezoneTest.testSelectExpressions(com.axibase.tsd.api.method.sql.clause.with.SqlWithTimezoneTest)
  Run 1: SqlWithTimezoneTest.testSelectExpressions:250->SqlTest.assertSqlQueryRows:137->SqlTest.assertSqlQueryRows:117->SqlMethod.queryTable:92->SqlMethod.queryTable:78 » IllegalState
```

**Comment by Arthasasyan** [comment]
```json
testEntityEscape(com.axibase.tsd.api.method.series.SeriesQueryEntityEscapeTest)  Time elapsed: 0.01 sec  <<< FAILURE!
java.lang.AssertionError: 
Incorrect series returned with filter *-1* expected:<{
  "entity" : "*?%_\\-1\\*\\?\\%\\_\\\\-2\\\\*\\\\?\\\\%\\\\_\\\\\\-3method-series-series-query-entity-escape-test-entity-1",
  "metric" : "method-series-series-query-entity-escape-test-metric-1",
  "data" : [ {
    "d" : "2017-08-01T00:00:00.000Z",
    "v" : 123.4567
  } ],
  "tags" : { },
  "type" : "HISTORY"
}> but was:<{
  "entity" : "*-1*",
  "metric" : "method-series-series-query-entity-escape-test-metric-1",
  "data" : [ ],
  "tags" : { },
  "type" : "HISTORY"
}>
	at com.axibase.tsd.api.method.series.SeriesQueryEntityEscapeTest.testEntityEscape(SeriesQueryEntityEscapeTest.java:60)
testEntityEscape(com.axibase.tsd.api.method.series.SeriesQueryEntityEscapeTest)  Time elapsed: 0.016 sec  <<< FAILURE!
java.lang.AssertionError: 
Incorrect series returned with filter \**-1* expected:<{
  "entity" : "*?%_\\-1\\*\\?\\%\\_\\\\-2\\\\*\\\\?\\\\%\\\\_\\\\\\-3method-series-series-query-entity-escape-test-entity-1",
  "metric" : "method-series-series-query-entity-escape-test-metric-1",
  "data" : [ {
    "d" : "2017-08-01T00:00:00.000Z",
    "v" : 123.4567
  } ],
  "tags" : { },
  "type" : "HISTORY"
}> but was:<{
  "entity" : "\\**-1*",
  "metric" : "method-series-series-query-entity-escape-test-metric-1",
  "data" : [ ],
  "tags" : { },
  "type" : "HISTORY"
}>
	at com.axibase.tsd.api.method.series.SeriesQueryEntityEscapeTest.testEntityEscape(SeriesQueryEntityEscapeTest.java:60)
Results :
Failed tests: 
com.axibase.tsd.api.method.series.SeriesQueryEntityEscapeTest.testEntityEscape(com.axibase.tsd.api.method.series.SeriesQueryEntityEscapeTest)
  Run 1: SeriesQueryEntityEscapeTest.testEntityEscape:60 Incorrect series returned with filter *-1* expected:<{
  "entity" : "*?%_\\-1\\*\\?\\%\\_\\\\-2\\\\*\\\\?\\\\%\\\\_\\\\\\-3method-series-series-query-entity-escape-test-entity-1",
  "metric" : "method-series-series-query-entity-escape-test-metric-1",
  "data" : [ {
    "d" : "2017-08-01T00:00:00.000Z",
    "v" : 123.4567
  } ],
  "tags" : { },
  "type" : "HISTORY"
}> but was:<{
  "entity" : "*-1*",
  "metric" : "method-series-series-query-entity-escape-test-metric-1",
  "data" : [ ],
  "tags" : { },
  "type" : "HISTORY"
}>
  Run 2: SeriesQueryEntityEscapeTest.testEntityEscape:60 Incorrect series returned with filter \**-1* expected:<{
  "entity" : "*?%_\\-1\\*\\?\\%\\_\\\\-2\\\\*\\\\?\\\\%\\\\_\\\\\\-3method-series-series-query-entity-escape-test-entity-1",
  "metric" : "method-series-series-query-entity-escape-test-metric-1",
  "data" : [ {
    "d" : "2017-08-01T00:00:00.000Z",
    "v" : 123.4567
  } ],
  "tags" : { },
  "type" : "HISTORY"
}> but was:<{
  "entity" : "\\**-1*",
  "metric" : "method-series-series-query-entity-escape-test-metric-1",
  "data" : [ ],
  "tags" : { },
  "type" : "HISTORY"
}>
```
